# Generated by Django 4.2.29 on 2026-03-23 18:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jira_account_id', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('google_credentials_encrypted', models.TextField(blank=True)),
                ('google_calendar_id', models.CharField(blank=True, max_length=255)),
                ('team_calendar_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jira_users',
            },
        ),
        migrations.CreateModel(
            name='SyncConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jira_project_key', models.CharField(max_length=50)),
                ('issue_types', models.JSONField(default=list)),
                ('sync_to_team_calendar', models.BooleanField(default=False)),
                ('team_calendar_id', models.CharField(blank=True, max_length=255)),
                ('additional_jql', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sync_configs',
            },
        ),
        migrations.CreateModel(
            name='SyncedIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jira_issue_key', models.CharField(max_length=50)),
                ('jira_issue_id', models.CharField(max_length=50)),
                ('google_event_id', models.CharField(max_length=255)),
                ('team_event_id', models.CharField(blank=True, max_length=255)),
                ('last_jira_update', models.DateTimeField(blank=True, null=True)),
                ('last_gcal_update', models.DateTimeField(blank=True, null=True)),
                ('is_personal', models.BooleanField(default=False)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('field_checksums', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_issues', to='sync.jirauser')),
            ],
            options={
                'db_table': 'synced_issues',
                'unique_together': {('jira_issue_key', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color_hex', models.CharField(default='#808080', max_length=7)),
                ('google_color_id', models.IntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='SyncHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=20)),
                ('source', models.CharField(choices=[('jira', 'Jira'), ('gcal', 'Google Calendar')], max_length=20)),
                ('field_changes', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conflict_detected', models.BooleanField(default=False)),
                ('synced_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sync.syncedissue')),
            ],
            options={
                'db_table': 'sync_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=50)),
                ('jira_value', models.TextField()),
                ('gcal_value', models.TextField()),
                ('jira_timestamp', models.DateTimeField()),
                ('gcal_timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('resolved_value', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='sync.syncedissue')),
            ],
            options={
                'db_table': 'conflicts',
            },
        ),
    ]
